apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
 name: house-price-api-monitor
 labels:
    release: prom
spec:
  selector:
    matchLabels:
      app: model
  namespaceSelector:
    matchNames:
    - default # or your namespace
  endpoints:
  - port: "8000" # or match name of your service port
    path: /metrics
    interval: 15s